name: dotnet package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: |
          dotnet restore
          cd SignalRWebpack
          npm install
          npm run release
      - name: Build
        run: dotnet build --configuration Release --no-restore